package by.training.gusakov.controller.command;

public enum CommandName {
    REGISTRATION,
    SIGN_IN,
    LOG_OUT,
    ADD_TRANSACTION,
    GET_ALL_TRANSACTIONS,
    GET_ALL_TRANSACTIONS_IN_A_PERIOD,
    GET_ALL_TRANSACTIONS_OF_CERTAIN_TYPE,
    GET_SUM_OF_TRANSACTIONS_OF_CERTAIN_TYPE,
    GET_ALL_TRANSACTIONS_OF_CERTAIN_TYPE_IN_A_PERIOD,
    GET_BALANCE
}
